version: "3.9"

services:
  # 🧠 Backend (Node.js + Express)
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ticketflow_api
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      DB_STORAGE: ./database.sqlite
    volumes:
      - ./backend:/app
      - ./data:/app/data
    command: npm run dev
    restart: always

  # 🎨 Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ticketflow_frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:4000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - api
    restart: always
