version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "4000:4000"
    volumes:
      - ./database.sqlite:/app/database.sqlite

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
